DholeraSirPages/urls.py
from django.urls import path , include


from . import views 


app_name = 'DholeraSirPages'

urlpatterns = [
    path('', views.index , name='index'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('Connectivtiy/' , views.connectivity , name='Connectivity'),
    path('Connectivtiy/<str:image_name>.jpg', views.image_view, name='image_view'),
    path('Dholera-Sir-Projects' , views.projects , name='Dholera-Sir-Projects'),
    path("Dholera-International-Airport/", views.AirPort, name="Dholera-International-Airport"),
    path('Dholera-solar-power-plant/' , views.Solar_plant , name='Dholera-solar-power-plant'),
    path('Dholera-metro-rail-project/' , views.Metro , name='Dholera-metro-rail-project'),
    path('ahmedabad-dholera-six-lane-expressway/' , views.Express , name='ahmedabad-dholera-six-lane-expressway'),
    path('Mega-Projects' , views.MegaProjects , name='Mega-Projects'),
    path('Dholera-Sir-Work-Progress' , views.PhotoGallery , name='Dholera-Sir-Work-Progress'),
    path('Dholera-sir-projects-update', views.RuCoProjects , name='Dholera-sir-projects-update' ),
    path('Dholera-Sir-Current-Status', views.CurrentStatus , name='Dholera-Sir-Current-Status' ),
    path('DMIC-Projects' , views.DMIC , name='DMIC-Projects'),
    path('DFC-Projects' , views.DFC , name='DFC-Projects'),
    path('GIDB' , views.GIDB , name='GIDB'),
    path('D-RDA' , views.DRDA , name='D-RDA')
    
]

Dholera_MetroCity/urls.py
from django.contrib import admin

from django.urls import path , include





urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
     path("" , include('core.urls')),
     path("about us/" , include('AboutUs.urls')),
    path('Download/' , include('download.urls')),
    path('Dholera-Sir/' , include('DholeraSirPages.urls')),
    path('News/' , include('NewsApps.urls')),
    path('Photo-Gallery/' , include('PhotoGallery.urls')),
    path('Blogs/', include("blog.urls")),
    path('OurProjects/' , include('ourProject.urls')),
    path('Consultancy/' , include('consultancy.urls')),
    path('Contact-Us/' , include('Contactus.urls')),
    #  path("about/" , include('core.urls'))
]

PhotoGallery/urls.py
from django.urls import path


from . import views


app_name = 'PhotoGallery'

urlpatterns = [
    
    path('' , views.index , name='index'),
    path('Investor-Visit/' , views.Investors , name='Investor-Visit'),
    path('Investor-Feedback/' , views.Feedback , name='Investor-Feedback'),
    path('DMC-Site-Progress/' , views.DMCSite , name='DMC-Site-Progress'),
    path('photo-gallery-Dholera-Metro-City/' , views.Dholera_images , name='photo-gallery-Dholera-Metro-City'),
    path('photo-gallery-summit-2017/' , views.Summit_2017 , name='photo-gallery-summit-2017'),
    path('photo-gallery-summit-2018/' , views.Summit_2018 , name='photo-gallery-summit-2018'),
    path('Video-Gallery/' , views.VideoGallery , name='Video-Gallery'),
]

blog/urls.py
from django.urls import path


from . import views


app_name = 'blog'

urlpatterns = [
    path("", views.index , name='index'),
    path('blog-2/' , views.blog_2 , name='blog-2'),
    path('resale-Booking-Status-Dholera-Metro-City/' , views.resale , name='resale-Booking-Status-Dholera-Metro-City')
 
]

DholeraSirPages/models.py
from django.db import models

# Create your models here.

PhotoGallery/models.py
from django.db import models

# Create your models here.

DholeraSirPages/views.py
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse
import os

# Create your views here.
def index(request):
    return render(request , 'dholera/dholeraSir.html')

def connectivity(request):
    return render(request , 'dholera/connectivity.html')





def image_view(request, image_name):
    if image_name == 'Road-Connectivity':
         image_path = os.path.join( settings.BASE_DIR, 'DholeraSirPages/static/dholeraSir-images/Conectivity/thumbnail/ways/Road_Connectivity_dholera_SIR.jpg')
    elif image_name =='Rail-Connectivity':
         image_path = os.path.join( settings.BASE_DIR, 'DholeraSirPages/static/dholeraSir-images/Conectivity/thumbnail/ways/Rail_Connectivity_dholera_SIR.jpg')
    elif image_name =='Air-Connectivity':
         image_path = os.path.join( settings.BASE_DIR, 'DholeraSirPages/static/dholeraSir-images/Conectivity/thumbnail/ways/Air_Connectivity_dholera_SIR.jpg')
    elif image_name =='Sea-Connectivity':
         image_path = os.path.join( settings.BASE_DIR, 'DholeraSirPages/static/dholeraSir-images/Conectivity/thumbnail/ways/Sea_Connectivity_dholera_SIR.jpg')
         
         
    with open(image_path, 'rb') as f:
        return HttpResponse(f.read(), content_type="image/jpeg")
    
    
    
def projects(request):
    return render(request , 'dholera/projects.html')

def AirPort(request):
    return render(request , 'dholera/dholera-Airport.html')

def Solar_plant(request):
    return render(request , 'dholera/solar-plant.html')

def Metro(request):
    return render(request , 'dholera/metro.html')

def Express(request):
    return render(request , 'dholera/express-way.html')

def MegaProjects(request):
    return render(request , 'dholera/mega-projects.html') 

def PhotoGallery(request):
    
    image_range = range(1, 36)  # Generate a range from 1 to 20
    context = {'image_range': image_range}
    return render(request , 'dholera/photo-gallery.html' , context) 

def RuCoProjects(request):
    return render(request , 'dholera/running-completedProjects.html')  

def CurrentStatus(request):
    return render(request , 'dholera/current-status.html')

def DMIC(request):
    return render(request ,  'dholera/DMIC.html')

def DFC(request):
    return render(request, 'dholera/DFC.html')

def GIDB(request):
    return render(request , 'dholera/GIDB.html')

def DRDA(request):
    return render(request , 'dholera/D-RDA.html')
    

PhotoGallery/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
   
    return render(request  , 'photo-pages/photo-gallery.html' , )


def Investors(request):
    PngRange = range(1,23)
    JpgRange = range(1,179)
    
    return render(request , 'photo-pages/investor-visit.html' , {
        'PngRange': PngRange,
        'JpgRange' : JpgRange 
    })
    
def Feedback(request):
    JpgRange = range(1,20)
    
    return render(request , 'photo-pages/investor-feedback.html' , {
          'JpgRange' : JpgRange 
    })
    
def DMCSite(request):
    image_range = range(1, 42)  # Generate a range from 1 to 20
    JpgImage = range(1,34)
    context = {'image_range': image_range,
               'JpgImage' : JpgImage
                }
    return render(request  , 'photo-pages/index.html' , context)

def Dholera_images(request):
    Dholeraimages = range(1, 10)
    return render(request , 'photo-pages/dholeraMetro.html' , {
        'Dholeraimages' :Dholeraimages
    })
    
def Summit_2017(request):
    SummitImages = range(2,19)
    
    return render(request , 'photo-pages/summit-2017.html' , {
        'SummitImages' :SummitImages
    })
    
def Summit_2018(request): 
    SummitImages = range(1,21)
    
    return render(request , 'photo-pages/summit-2018.html' , {
        'SummitImages' :SummitImages
    })
    
def VideoGallery(request):
    return render(request , 'photo-pages/video-gallery.html')

DholeraSirPages/templates/dholera/D-RDA.html
{% extends 'core/base.html' %}

{% load static %}


{% block title %}
D-RDA | Dholera Metro City  

{% endblock title %}

{% block content %}
    
<div>
    <div>
      <img id="myImage" class="w-full h-auto max-sm:h-36" src="" alt="">
    </div>
    <script>
      function changeImage() {
        var image = document.getElementById("myImage");
        if (window.innerWidth < 700) {
          image.src = "{% static 'dholeraSir-images\DRDA\DRDA_header_m.jpg' %}"; // Replace with the path to the new image
        } else {
          image.src = "{% static 'dholeraSir-images\DRDA\DRDA_header.jpg' %}"; // Replace with the original image path
        }
      }
  
      window.addEventListener("load", changeImage);
      window.addEventListener("resize", changeImage);
    </script>
  </div>


  <section class="mt-5 px-6 font-semibold text-gray-600 leading-8">
    <div  class="  flex items-center flex-row  gap-3">

        <img style="width: auto; height: 2.8rem;" src="{% static 'images\Download page\arrow-right-icon.png' %}" alt="">
    
        <div>
    
          <h1 class="text-2xl  max-md:text-xl font-bold text-purple-800">
            DHOLERA - REGIONAL DEVELOPMENT AUTHORITY
          </h1>
        </div>
      </div>


      <div class=" mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            The State Government will constitute RDA for each SIR declared by it.

          </h1>
        </div>

      </div>

      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            The RDA will be a body corporate.

          </h1>
        </div>
      </div>


      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            The State Government is also empowered to designate any Government agency or a govt. company to act as RDA.

          </h1>
        </div>
      </div>

      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            The RDA will have Chairman, Vice Chairman, CEO and members not exceeding eleven- to be appointed by the Govt. Dholera Metro CityIt will comprise of the official and non-officials & experts as members.

          </h1>
        </div>
      </div>


      <div id="" class="mt-10  flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.8rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">
    
        <div>
    
          <h1 class="text-blue-900 text-xl  font-bold">
            Power and functions of D-RDA
    
          </h1>
        </div>
      </div>

      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            To prepare Land use plan, Town planning scheme and Development plan for SIR.

          </h1>
        </div>
      </div>


      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            To Supervise, Monitor, Regulate and Ensure the planned development of SIR.
          </h1>
        </div>
      </div>


      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            To lay down the infrastructure and civil amenities.

          </h1>
        </div>
      </div>


      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            Acquire land and hold properties and sale, lease and transfer the properties including land.

          </h1>
        </div>
      </div>



      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            To execute contracts with unit holders, developers.

          </h1>
        </div>
      </div>


      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            To levy and collect fees, user charges. Control the development activities.

          </h1>
        </div>
      </div>


      <div class="mt-4 flex items-center flex-row  gap-3">

        <img style="width: auto; height: 1.2rem;" src="{% static 'dholeraSir-images\arw.jpg' %}" alt="">

        <div>

          <h1 class="">
            To remove unauthorized construction, encroachment. Basically all ground level work, planning & regulation.

          </h1>
        </div>
      </div>


  </section>


{% endblock content %}

DholeraSirPages/templates/dholera/GIDB.html
{% extends 'core/base.html' %}

{% load static %}


{% block title %}

GIDB | Dholera Metro City

{% endblock title %}

{% block content %}

<div>
    <div>
      <img id="myImage" class="w-full h-auto max-sm:h-36" src="" alt="">
    </div>
    <script>
      function changeImage() {
        var image = document.getElementById("myImage");
        if (window.innerWidth < 700) {
          image.src = "{% static 'dholeraSir-images\GIDB\gidb_header_m.jpg' %}"; // Replace with the path to the new image
        } else {
          image.src = "{% static 'dholeraSir-images\GIDB\gidb_header.jpg' %}"; // Replace with the original image path
        }
      }
  
      window.addEventListener("load", changeImage);
      window.addEventListener("resize", changeImage);
    </script>
  </div>

  <section class="mt-6 px-4">
    <div  class="  flex items-center flex-row  gap-3">

        <img style="width: auto; height: 2.8rem;" src="{% static 'images\Download page\arrow-right-icon.png' %}" alt="">
    
        <div>
    
          <h1 class="text-2xl  max-md:text-xl font-bold text-purple-800">
            GIDB - NODAL AGENCY
          </h1>
        </div>
      </div>

      <p class="mt-4 font-semibold text-gray-600 leading-8">Gujarat Infrastructure Development Board (GIDB) headed by Hon. CM will be the Apex Authority. GIDB can delegate such powers and functions to its Executive Committee headed by Hon. MOS (Ind) . Core functions of the Apex Authority like approval and modification in development plan, town planning scheme and general development regulations shall not be delegated to any committees. Powers and functions of the Apex Authority.</p>
  </section>


  <section class="mt-10 ">
     
    <div class="flex flex-grow justify-center  flex-wrap  gap-[3.5rem]">
      <div class="py-5 px-1 w-[10rem] text-center rounded-lg shadow-2xl bg-sky-700 text-white">
        <h1 class="text-2xl font-semibold">DMIC PROJECTS</h1>
        <p class="mt-5 text-base font-semibold">Delhi Mumbai Industrial Corridor</p>
      </div>


      <div class="py-5 px-1 w-[10rem] text-center rounded-lg shadow-2xl bg-sky-700 text-white">
        <h1 class="text-2xl font-semibold">DFC PROJECTS</h1>
        <p class="mt-5 text-base  font-semibold">Dedicated Freight Corridor</p>
      </div>


      <div class="py-5 px-1 w-[10rem] text-center rounded-lg shadow-2xl bg-sky-700 text-white">
        <h1 class="text-2xl font-semibold">GIDB</h1>
        <p class="mt-5 text-base  font-semibold">Gujarat infrastructure Development Board</p>
      </div>


      <div class="py-5 px-1 w-[10rem] text-center rounded-lg shadow-2xl bg-sky-700 text-white">
        <h1 class="text-2xl font-semibold">D-RDA</h1>
        <p class="mt-5  text-base font-semibold">Dholera - Regional Development Authority</p>
      </div>



      <div class="py-5 px-1 w-[10rem] text-center rounded-lg shadow-2xl bg-sky-700 text-white">
        <h1 class="text-2xl font-semibold">Dholera Sir</h1>
        <p class="mt-5 text-base  font-semibold">Special Investment Region</p>
      </div>


      <div class="py-5 px-1 w-[10rem] text-center rounded-lg shadow-2xl bg-sky-700 text-white">
        <h1 class="text-2xl font-semibold">Early Bird Projects</h1>
      </div>

      
    </div>
  </section>

{% endblock content %}

DholeraSirPages/templates/dholera/connectivity.html
{% extends 'core/base.html' %}


{% load static %}

{% block title %}
  
Connectivity | Dholera Metro City

{% endblock title %}

{% block content %}


<div>
    <div>
      <img class="w-full h-auto max-sm:h-36" src="{% static 'dholeraSir-images\Conectivity\conectivity_dholera_sir_header.jpg' %}" alt="">
    </div>
  </div>



  <div class="mt-20 px-16">

    <div class="flex items-center justify-center flex-grow gap-10 flex-initial flex-wrap">


      <div>
        <a href="{% url 'DholeraSirPages:image_view' 'Road-Connectivity' %}">
        <img class="border-[3px] border-purple-900 rounded-2xl shadow-2xl" src="{% static 'dholeraSir-images\Conectivity\thumbnail\Road_Connectivity_dholera_SIR_s.jpg' %}" alt="">
      </a>
      </div>

      <div>
        <a href="{% url 'DholeraSirPages:image_view' 'Air-Connectivity' %}">
        <img class="border-[3px] border-purple-900 rounded-2xl shadow-2xl" src="{% static 'dholeraSir-images\Conectivity\thumbnail\Air_Connectivity_Dholera_SIR_s.jpg' %}" alt="">
        </a>
      </div>

      <div>
        <a href="{% url 'DholeraSirPages:image_view' 'Rail-Connectivity' %}">
        <img class="border-[3px] border-purple-900 rounded-2xl shadow-2xl" src="{% static 'dholeraSir-images\Conectivity\thumbnail\Rail_Connectivity_Dholera_SIR_s.jpg' %}" alt="">
</a>
      </div>

      <div>
        <a href="{% url 'DholeraSirPages:image_view' 'Sea-Connectivity' %}">
        <img class="border-[3px] border-purple-900 rounded-2xl shadow-2xl" src="{% static 'dholeraSir-images\Conectivity\thumbnail\Sea_Connectivity_Dholera_SIR_s.jpg' %}" alt="">
        </a>
      </div>

    </div>

  </div>







{% endblock content %}

DholeraSirPages/templates/dholera/express-way.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}

Express Way | Dholera Metro City

{% endblock title %}

{% block content %}


<div>

  <div>
    <img  id="myImage" class="w-full max-sm:w-auto h-36" src="" alt="">
  </div>

  <script>
    function changeImage() {
      var image = document.getElementById("myImage");
      if (window.innerWidth < 700) {
        image.src = "{% static 'dholeraSir-images\DholeraSir-projects\dholera-international-airport\express-way\ahmedabad-dholera-express-way-header-m.jpg' %}"; // Replace with the path to the new image
      } else {
        image.src = "{% static 'dholeraSir-images\DholeraSir-projects\dholera-international-airport\express-way\ahmedabad-dholera-express-way-header.jpg' %}"; // Replace with the original image path
      }
    }

    window.addEventListener("load", changeImage);
    window.addEventListener("resize", changeImage);
  </script>
</div>


<div class="mt-5">

  <div class="bg-green-300 py-3 text-center text-black font-semibold text-xl">
    <h1>Six Lane Expressway</h1>
  </div>
</div>

<div class="mt-8 px-10 max-sm:px-3">

  <div class=" float-left m-[10px]">
    <img class=" shadow-xl rounded-lg" src="{% static 'dholeraSir-images\DholeraSir-projects\dholera-international-airport\express-way\early_project_1_img.jpg' %}" alt="">
  </div>

  <div style="letter-spacing: 0.4px;" class="font-semibold text-gray-600 text-base py-5 leading-6 ">
    <p>
      A six lane dual carriageway highway shall be built with provisions to extend it up to 10 lanes in Gujarat Dholera Metro city. Initially, it shall be built in a 4 lane format with two lanes on each side and shall be further extended in due time. This project had been proposed in the master plan of the Delhi Mumbai
    </p>

    <p class="mt-5">
      Industrial Corridor and approved by the central government and shall incur an estimated project cost of Rs. 900.39 crores.


    </p>


    <p class="mt-5">
      Dholera SIR project shall be divided into six town planning schemes and shall be built in three different phases based on the economic activities that shall occur in each phase of development. The last of all phase is expected to get completed by 2040. By such time, Dholera Project shall be home to 2 million people. These people shall be supported by over 8 lakh employment opportunities that shall be generated from the industrial and manufacturing units that shall be developed in the city. As per sources, Dholera is being envisaged as a global trading and manufacturing hub.

    </p>


    <p class="mt-5">
      As the 100 smart cities shall embark on their journey of creating a better India, Dholera SIR Project shall light the way for them.


    </p>

    <!--

      -->
    <div class="mt-20">


      <table class="border border-x-0 border-t-0  p-5 text-blue-900 font-semibold text-lg">

        <caption>Expected IRR of the project</caption>



        <tr class="border border-x-0">
          <td class="p-4">Economic IRR</td>
          <td class="pl-96 max-md:pl-20"> 31.60%</td>


        </tr>

        <tr class="border border-x-0">
          <td class="p-4">Project IRR</td>
          <td class="pl-96 max-md:pl-20"> 12.00%</td>


        </tr>


        <tr class="border border-x-0">
          <td class="p-4">Equity IRR</td>
          <td class="pl-96 max-md:pl-20"> 12.32%</td>


        </tr>

      </table>


    </div>


    <p class="mt-5">
      The project shall be developed under complete authority of a special purpose vehicle(GoG owned). This vehicle shall undertake and complete crucial tasks such as acquiring land for development of metro corridor, metro stations and bus stations. It shall also be responsible for seamless shifting of the utilities in a phased manner. The special purpose vehicle has been formed with an initial paid up capital of Rupees 10 Crores and authorized capital of Rupees 200 Crores. The SPV shall also own responsibility of discussing the funding pattern for the project with both state and central government and finalizing it thereafter.
    </p>

    <p class="mt-5">

      The smart city Dholerametro project is expected to be a carrier of 80,000 passengers per hour (40,000 in each direction) and 1.70 million commuters are expected to use by the year 2031.


    </p>





  </div>

</div>




{% endblock content %}

DholeraSirPages/templates/dholera/photo-gallery.html
{% extends 'core/base.html' %}

{% load static %}



{% block title %}

Progress | Dholera Metro City

{% endblock title %}

{% block content %}



<div>
  <div>
    <img id="myImage" class="w-full h-auto max-sm:h-36" src="" alt="">
  </div>
  <script>
    function changeImage() {
      var image = document.getElementById("myImage");
      if (window.innerWidth < 700) {
        image.src = "{% static 'dholeraSir-images\photo-gallery\dholera-sir-work-progress-header-m.jpg' %}"; // Replace with the path to the new image
      } else {
        image.src = "{% static 'dholeraSir-images\photo-gallery\dholera-sir-work-progress-header.jpg' %}"; // Replace with the original image path
      }
    }

    window.addEventListener("load", changeImage);
    window.addEventListener("resize", changeImage);
  </script>
</div>


<section class="mt-8 px-6">


  <div class="flex items-center justify-center">
    <iframe width="90%" height="515" src="https://www.youtube-nocookie.com/embed/ijxH5BBBUrQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  </div>



  <div class="mt-6">
<div class="flex flex-initial flex-wrap flex-grow items-center justify-center gap-7">


    {% for image_number in image_range %}
    <a href="{% static 'dholeraSir-images\photo-gallery\progress-' %}{{ image_number }}.jpeg" target="_blank">
    <img style="border: 3px dotted orange;" class="rounded-lg" src="{% static 'dholeraSir-images\photo-gallery\progress-' %}{{ image_number }}.jpeg" alt="Image {{ image_number }}">
    </a>
    {% endfor %}

</div>

<div class=" text-base font-semibold mt-8 flex flex-row  justify-center gap-3">
    <h1>For More Photos Contact us :  </h1>
    <div>

        <span class="text-blue-600">info@dholerametro.in</span>  <br><span class="text-blue-600">8866333000</span>
    </div>
   

   </div>
  </div>

</section>




<section style="margin-top: 10rem;" class="px-7">
  <div  class="flex flex-wrap  gap-10 items-center justify-center ">

    <a class="" href="{%  url 'DholeraSirPages:Dholera-Sir-Work-Progress' %}">
      <img src="{% static 'gallery\photos\site_progress_tag.jpg' %}" alt="site_progress_tag"> </a>

    <a href="{% url 'PhotoGallery:DMC-Site-Progress' %}">
      <img src="{% static 'gallery\photos\site_progress.jpg' %}" alt="site_progress"></a>

    <a href="{% url 'PhotoGallery:Investor-Visit' %}">
      <img src="{% static 'gallery\photos\investor-visit-memories.jpg' %}" alt="investor-visit-memories"></a>

    <a href="{% url 'PhotoGallery:photo-gallery-Dholera-Metro-City' %}">
      <img src="{% static  'gallery\photos\Dholera_Metro_City.jpg' %}" alt="Dholera_Metro_City"></a>

    <a href="{% url 'PhotoGallery:photo-gallery-summit-2017' %}">
      <img src="{% static 'gallery\photos\summit_2017.jpg' %}" alt="summit_2017"></a>

    <a href="{% url 'PhotoGallery:photo-gallery-summit-2018' %}">
      <img src="{% static 'gallery\photos\gpbs-summit.jpg' %}" alt="gpbs-summit"></a>




  </div>

</section>




{% endblock content %}

DholeraSirPages/templates/dholera/projects.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}

Projects | Dholera Metro City

{% endblock title %}

{% block content %}
    

<div>
    <div>
      <img id="myImage" class="w-full " src="" alt="">
    </div>

    <script>
      function changeImage() {
          var image = document.getElementById("myImage");
          if (window.innerWidth < 700) {
            image.src = "{% static 'dholeraSir-images\DholeraSir-projects\Dholera_SIR_Header_m.jpg' %}"; // Replace with the path to the new image
          } else {
            image.src = "{% static 'dholeraSir-images\Dholera_SIR_Header.jpg' %}"; // Replace with the original image path
          }
        }
    
        window.addEventListener("load", changeImage);
        window.addEventListener("resize", changeImage);
      </script>
  </div>


  <div class="mt-10 px-16">

    <div class="flex items-center justify-center flex-grow gap-20 flex-initial flex-wrap">

        <div>
           
            <img class=" shadow-2xl" src="{% static 'dholeraSir-images\DholeraSir-projects\projects\abcd-building-dholera-sir.jpg' %}" alt="">
          
          </div>

          <div>
            <a href="{% url 'DholeraSirPages:Dholera-International-Airport'  %}">
            <img class=" shadow-2xl" src="{% static 'dholeraSir-images\DholeraSir-projects\projects\dholera-international-airport.jpg' %}" alt="">
          </a>
          </div>


          <div>
            <a href="{% url 'DholeraSirPages:Dholera-solar-power-plant' %}">
            <img class=" shadow-2xl" src="{% static 'dholeraSir-images\DholeraSir-projects\projects\solar-park-dholera-sir.jpg' %}" alt="">
          </a>
          </div>

          <div>
            <a href="{% url 'DholeraSirPages:Dholera-metro-rail-project' %}">
            <img class=" shadow-2xl" src="{% static 'dholeraSir-images\DholeraSir-projects\projects\dholera-metro-train.jpg' %}" alt="">
          </a>
          </div>

          <div>
            <a href="{% url 'DholeraSirPages:ahmedabad-dholera-six-lane-expressway' %}">
            <img class=" shadow-2xl" src="{% static 'dholeraSir-images\DholeraSir-projects\projects\express-way-dholera-sir.jpg' %}" alt="">
          </a>
          </div>



    </div>

  </div>




{% endblock content %}